### Create a pharmacy

POST http://localhost:5000/api/pharmacies
Content-Type: application/json

{
  "name": "PharmaLink Test Pharmacy",
  "address": "Cebu City, Philippines",
  "contact_number": "09123456789",
  "email": "test@pharmalink.com"
}


### Update pharmacy

PATCH http://localhost:5000/api/pharmacies/1
Content-Type: application/json

{
  "contact_number": "09987654321"
}


### Test invalid pharmacy - missing name

POST http://localhost:5000/api/pharmacies
Content-Type: application/json

{
  "name": "",
  "address": "Cebu City, Philippines",
  "contact_number": "09123456789",
  "email": "invalid-test@pharmalink.com"
}

### Test invalid pharmacy update - empty name

PATCH http://localhost:5000/api/pharmacies/1
Content-Type: application/json

{
  "name": ""
}

### Login test

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@pharmalink.com",
  "password": "Admin123!"
}

### Test protected authentication endpoint

GET http://localhost:5000/api/test-auth
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk1OTk4LCJpYXQiOjE3ODY1OTIzOTgsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5MjM5OH1dLCJzZXNzaW9uX2lkIjoiNDA0MWFiMzQtMDc5MS00YTljLTljZGQtMDczNTkwMGY3MDQ4IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.jvytrfZD5Vl4TA-RfsmNgWUvg3-A-zeYIJV9Ti4q-ymiveKAb_-HF8icsjCwUsKbSlWDQdN3g-gvNkJ3aaoZ5w

### Test authenticated PharmaLink user

GET http://localhost:5000/api/test-user
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk1OTk4LCJpYXQiOjE3ODY1OTIzOTgsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5MjM5OH1dLCJzZXNzaW9uX2lkIjoiNDA0MWFiMzQtMDc5MS00YTljLTljZGQtMDczNTkwMGY3MDQ4IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.jvytrfZD5Vl4TA-RfsmNgWUvg3-A-zeYIJV9Ti4q-ymiveKAb_-HF8icsjCwUsKbSlWDQdN3g-gvNkJ3aaoZ5w

### Test role authorization

GET http://localhost:5000/api/test-role
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk1OTk4LCJpYXQiOjE3ODY1OTIzOTgsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5MjM5OH1dLCJzZXNzaW9uX2lkIjoiNDA0MWFiMzQtMDc5MS00YTljLTljZGQtMDczNTkwMGY3MDQ4IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.jvytrfZD5Vl4TA-RfsmNgWUvg3-A-zeYIJV9Ti4q-ymiveKAb_-HF8icsjCwUsKbSlWDQdN3g-gvNkJ3aaoZ5w

### Create pharmacy - authenticated SUPER_ADMIN

POST http://localhost:5000/api/pharmacies
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk1OTk4LCJpYXQiOjE3ODY1OTIzOTgsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5MjM5OH1dLCJzZXNzaW9uX2lkIjoiNDA0MWFiMzQtMDc5MS00YTljLTljZGQtMDczNTkwMGY3MDQ4IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.jvytrfZD5Vl4TA-RfsmNgWUvg3-A-zeYIJV9Ti4q-ymiveKAb_-HF8icsjCwUsKbSlWDQdN3g-gvNkJ3aaoZ5w
Content-Type: application/json

{
  "name": "PharmaLink Protected Test Pharmacy",
  "address": "Cebu City, Philippines",
  "contact_number": "09112223333",
  "email": "protected@test.pharmalink.com"
}

### Update pharmacy - authenticated SUPER_ADMIN

PATCH http://localhost:5000/api/pharmacies/1
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk1OTk4LCJpYXQiOjE3ODY1OTIzOTgsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5MjM5OH1dLCJzZXNzaW9uX2lkIjoiNDA0MWFiMzQtMDc5MS00YTljLTljZGQtMDczNTkwMGY3MDQ4IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.jvytrfZD5Vl4TA-RfsmNgWUvg3-A-zeYIJV9Ti4q-ymiveKAb_-HF8icsjCwUsKbSlWDQdN3g-gvNkJ3aaoZ5w
Content-Type: application/json

{
  "contact_number": "09876543210"
}

### Public pharmacy list

GET http://localhost:5000/api/pharmacies

### Create Pharmacy Admin

POST http://localhost:5000/api/users/pharmacy-admin
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk1OTk4LCJpYXQiOjE3ODY1OTIzOTgsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5MjM5OH1dLCJzZXNzaW9uX2lkIjoiNDA0MWFiMzQtMDc5MS00YTljLTljZGQtMDczNTkwMGY3MDQ4IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.jvytrfZD5Vl4TA-RfsmNgWUvg3-A-zeYIJV9Ti4q-ymiveKAb_-HF8icsjCwUsKbSlWDQdN3g-gvNkJ3aaoZ5w
Content-Type: application/json

{
  "pharmacy_id": 1,
  "first_name": "Pharmacy",
  "last_name": "Admin",
  "email": "pharmacyadmin@pharmalink.com",
  "phone": "09123456789",
  "password": "PharmacyAdmin123!"
}

### Reactivate pharmacy

PATCH http://localhost:5000/api/pharmacies/1
eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk4MDgyLCJpYXQiOjE3ODY1OTQ0ODIsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5NDQ4Mn1dLCJzZXNzaW9uX2lkIjoiMzFjOWM4YjUtZDljMi00NGY3LTgxYTgtOGJjMGUwZWUzYmNlIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.KoJ_YUlylDzKayPwbvaVLnlCXcys4hkkjyljGLPR4lvmyjZZYW8skWgKRSBN9QrUvUbL5oJb8pWZGzz0yRklgw
Content-Type: application/json

{
  "status": "ACTIVE"
}

### Login as Super Admin

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@pharmalink.com",
  "password": "Admin123!"
}


### Reactivate pharmacy
PATCH http://localhost:5000/api/pharmacies/1
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk4NjQxLCJpYXQiOjE3ODY1OTUwNDEsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5NTA0MX1dLCJzZXNzaW9uX2lkIjoiMzBkOTA3MDktNTA0OS00OWIxLWFmZWQtNjc1MmEyOWUxM2JiIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.j0pXZds8BWVc1cjyF7_cr6dIPvy8xhMftVA1XGt7xfwkJQWLIRbddUKwurKDAmx4dDywwoVr2RVBsVj0vif1ZA
Content-Type: application/json

{
  "status": "ACTIVE"
}

### Create Pharmacy Admin

POST http://localhost:5000/api/users/pharmacy-admin
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk4NjQxLCJpYXQiOjE3ODY1OTUwNDEsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5NTA0MX1dLCJzZXNzaW9uX2lkIjoiMzBkOTA3MDktNTA0OS00OWIxLWFmZWQtNjc1MmEyOWUxM2JiIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.j0pXZds8BWVc1cjyF7_cr6dIPvy8xhMftVA1XGt7xfwkJQWLIRbddUKwurKDAmx4dDywwoVr2RVBsVj0vif1ZA
Content-Type: application/json

{
  "pharmacy_id": 1,
  "first_name": "Pharmacy",
  "last_name": "Admin",
  "email": "pharmacyadmin@pharmalink.com",
  "phone": "09123456789",
  "password": "PharmacyAdmin123!"
}

### Login as Pharmacy Admin

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "pharmacyadmin@pharmalink.com",
  "password": "PharmacyAdmin123!"
}


### Test Pharmacy Admin role

GET http://localhost:5000/api/test-role
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5YTk2MmQwMC05NGU2LTQyNGYtYWQwNC02ZjcyYjAwZDY2OGYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NjQyMTc1LCJpYXQiOjE3ODY2Mzg1NzUsImVtYWlsIjoicGhhcm1hY3lhZG1pbkBwaGFybWFsaW5rLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzg2NjM4NTc1fV0sInNlc3Npb25faWQiOiI0NWM1MTE3MS04NmQ1LTRmN2EtOTk5OC0zY2UwZjIxODhjNTYiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.O-L6zFHOJm8tkKZQ-VOXz5xQqF-iY-l3XYVsChYHED19UwswZBGP9gj1mbNUM-KMd-fJucUfSMiqSEzIpozqeg

### Login as Pharmacy Admin

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "pharmacyadmin@pharmalink.com",
  "password": "PharmacyAdmin123!"
}

### Get Pharmacy 1 Inventory

GET http://localhost:5000/api/pharmacies/1/inventory
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5YTk2MmQwMC05NGU2LTQyNGYtYWQwNC02ZjcyYjAwZDY2OGYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NjQzNTc4LCJpYXQiOjE3ODY2Mzk5NzgsImVtYWlsIjoicGhhcm1hY3lhZG1pbkBwaGFybWFsaW5rLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzg2NjM5OTc4fV0sInNlc3Npb25faWQiOiJlYTRlMjc4MC01NDU4LTQ3YjMtOTRhNy1iNWI1YzMxOWZkMmQiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.JjHUK98due92emw0pCVWEeN7VCywPRN9UIHKAjis6uMLj2yB5NmooSOedVSqxa9Io0VKn5oSES91LcCDzpshrA

### Login as Pharmacy Admin
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "pharmacyadmin@pharmalink.com",
  "password": "PharmacyAdmin123!"
}

### Get Pharmacy 1 Inventory
GET http://localhost:5000/api/pharmacies/1/inventory
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5YTk2MmQwMC05NGU2LTQyNGYtYWQwNC02ZjcyYjAwZDY2OGYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NjQzNzg0LCJpYXQiOjE3ODY2NDAxODQsImVtYWlsIjoicGhhcm1hY3lhZG1pbkBwaGFybWFsaW5rLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzg2NjQwMTg0fV0sInNlc3Npb25faWQiOiI0Mjk4Yjk5MC00MDI1LTQ5N2EtYmRmZS01YWE1MjFjZGEyMmMiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.fLw_td3A8Oq-T6wo2P_NfaPIQfa5M3kgYSURae93UKKhdeuSEfpU6uVjZEkwk2titIIjmzN91gQ5ZxInj6gviQ

### Login as Pharmacy Admin

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "pharmacyadmin@pharmalink.com",
  "password": "PharmacyAdmin123!"
}

###

### Get Pharmacy 1 Inventory
GET http://localhost:5000/api/pharmacies/1/inventory
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5YTk2MmQwMC05NGU2LTQyNGYtYWQwNC02ZjcyYjAwZDY2OGYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NjQ0NjI0LCJpYXQiOjE3ODY2NDEwMjQsImVtYWlsIjoicGhhcm1hY3lhZG1pbkBwaGFybWFsaW5rLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzg2NjQxMDI0fV0sInNlc3Npb25faWQiOiJiODMyMjViNC01NTVkLTQwMTEtOGM3OS02YTM0Nzc1ZmExYzIiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.g_o9D24SaFcE9Ppn6Gn8h2Ow7O29KovIevY4bwAOmrIzApnpYea2xIOGTbdQX2seCzu1_Ox9pSyRftMlKv3AQA