### Create a pharmacy

POST http://localhost:5000/api/pharmacies
Content-Type: application/json

{
  "name": "PharmaLink Test Pharmacy",
  "address": "Cebu City, Philippines",
  "contact_number": "09123456789",
  "email": "test@pharmalink.com"
}


### Update pharmacy

PATCH http://localhost:5000/api/pharmacies/1
Content-Type: application/json

{
  "contact_number": "09987654321"
}


### Test invalid pharmacy - missing name

POST http://localhost:5000/api/pharmacies
Content-Type: application/json

{
  "name": "",
  "address": "Cebu City, Philippines",
  "contact_number": "09123456789",
  "email": "invalid-test@pharmalink.com"
}

### Test invalid pharmacy update - empty name

PATCH http://localhost:5000/api/pharmacies/1
Content-Type: application/json

{
  "name": ""
}

### Login test

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@pharmalink.com",
  "password": "Admin123!"
}

### Test protected authentication endpoint

GET http://localhost:5000/api/test-auth
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk1OTk4LCJpYXQiOjE3ODY1OTIzOTgsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5MjM5OH1dLCJzZXNzaW9uX2lkIjoiNDA0MWFiMzQtMDc5MS00YTljLTljZGQtMDczNTkwMGY3MDQ4IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.jvytrfZD5Vl4TA-RfsmNgWUvg3-A-zeYIJV9Ti4q-ymiveKAb_-HF8icsjCwUsKbSlWDQdN3g-gvNkJ3aaoZ5w

### Test authenticated PharmaLink user

GET http://localhost:5000/api/test-user
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk1OTk4LCJpYXQiOjE3ODY1OTIzOTgsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5MjM5OH1dLCJzZXNzaW9uX2lkIjoiNDA0MWFiMzQtMDc5MS00YTljLTljZGQtMDczNTkwMGY3MDQ4IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.jvytrfZD5Vl4TA-RfsmNgWUvg3-A-zeYIJV9Ti4q-ymiveKAb_-HF8icsjCwUsKbSlWDQdN3g-gvNkJ3aaoZ5w

### Test role authorization

GET http://localhost:5000/api/test-role
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk1OTk4LCJpYXQiOjE3ODY1OTIzOTgsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5MjM5OH1dLCJzZXNzaW9uX2lkIjoiNDA0MWFiMzQtMDc5MS00YTljLTljZGQtMDczNTkwMGY3MDQ4IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.jvytrfZD5Vl4TA-RfsmNgWUvg3-A-zeYIJV9Ti4q-ymiveKAb_-HF8icsjCwUsKbSlWDQdN3g-gvNkJ3aaoZ5w

### Create pharmacy - authenticated SUPER_ADMIN

POST http://localhost:5000/api/pharmacies
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk1OTk4LCJpYXQiOjE3ODY1OTIzOTgsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5MjM5OH1dLCJzZXNzaW9uX2lkIjoiNDA0MWFiMzQtMDc5MS00YTljLTljZGQtMDczNTkwMGY3MDQ4IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.jvytrfZD5Vl4TA-RfsmNgWUvg3-A-zeYIJV9Ti4q-ymiveKAb_-HF8icsjCwUsKbSlWDQdN3g-gvNkJ3aaoZ5w
Content-Type: application/json

{
  "name": "PharmaLink Protected Test Pharmacy",
  "address": "Cebu City, Philippines",
  "contact_number": "09112223333",
  "email": "protected@test.pharmalink.com"
}

### Update pharmacy - authenticated SUPER_ADMIN

PATCH http://localhost:5000/api/pharmacies/1
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk1OTk4LCJpYXQiOjE3ODY1OTIzOTgsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5MjM5OH1dLCJzZXNzaW9uX2lkIjoiNDA0MWFiMzQtMDc5MS00YTljLTljZGQtMDczNTkwMGY3MDQ4IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.jvytrfZD5Vl4TA-RfsmNgWUvg3-A-zeYIJV9Ti4q-ymiveKAb_-HF8icsjCwUsKbSlWDQdN3g-gvNkJ3aaoZ5w
Content-Type: application/json

{
  "contact_number": "09876543210"
}

### Public pharmacy list

GET http://localhost:5000/api/pharmacies

### Create Pharmacy Admin

POST http://localhost:5000/api/users/pharmacy-admin
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk1OTk4LCJpYXQiOjE3ODY1OTIzOTgsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5MjM5OH1dLCJzZXNzaW9uX2lkIjoiNDA0MWFiMzQtMDc5MS00YTljLTljZGQtMDczNTkwMGY3MDQ4IiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.jvytrfZD5Vl4TA-RfsmNgWUvg3-A-zeYIJV9Ti4q-ymiveKAb_-HF8icsjCwUsKbSlWDQdN3g-gvNkJ3aaoZ5w
Content-Type: application/json

{
  "pharmacy_id": 1,
  "first_name": "Pharmacy",
  "last_name": "Admin",
  "email": "pharmacyadmin@pharmalink.com",
  "phone": "09123456789",
  "password": "PharmacyAdmin123!"
}

### Reactivate pharmacy

PATCH http://localhost:5000/api/pharmacies/1
eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk4MDgyLCJpYXQiOjE3ODY1OTQ0ODIsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5NDQ4Mn1dLCJzZXNzaW9uX2lkIjoiMzFjOWM4YjUtZDljMi00NGY3LTgxYTgtOGJjMGUwZWUzYmNlIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.KoJ_YUlylDzKayPwbvaVLnlCXcys4hkkjyljGLPR4lvmyjZZYW8skWgKRSBN9QrUvUbL5oJb8pWZGzz0yRklgw
Content-Type: application/json

{
  "status": "ACTIVE"
}

### Login as Super Admin

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "admin@pharmalink.com",
  "password": "Admin123!"
}


### Reactivate pharmacy
PATCH http://localhost:5000/api/pharmacies/1
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk4NjQxLCJpYXQiOjE3ODY1OTUwNDEsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5NTA0MX1dLCJzZXNzaW9uX2lkIjoiMzBkOTA3MDktNTA0OS00OWIxLWFmZWQtNjc1MmEyOWUxM2JiIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.j0pXZds8BWVc1cjyF7_cr6dIPvy8xhMftVA1XGt7xfwkJQWLIRbddUKwurKDAmx4dDywwoVr2RVBsVj0vif1ZA
Content-Type: application/json

{
  "status": "ACTIVE"
}

### Create Pharmacy Admin

POST http://localhost:5000/api/users/pharmacy-admin
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI3NTlkYzVlNi03NDMwLTRlMjAtODQ0MS1mNGI2OTg4YzJlZWYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NTk4NjQxLCJpYXQiOjE3ODY1OTUwNDEsImVtYWlsIjoiYWRtaW5AcGhhcm1hbGluay5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlfSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQiLCJhYWwiOiJhYWwxIiwiYW1yIjpbeyJtZXRob2QiOiJwYXNzd29yZCIsInRpbWVzdGFtcCI6MTc4NjU5NTA0MX1dLCJzZXNzaW9uX2lkIjoiMzBkOTA3MDktNTA0OS00OWIxLWFmZWQtNjc1MmEyOWUxM2JiIiwiaXNfYW5vbnltb3VzIjpmYWxzZX0.j0pXZds8BWVc1cjyF7_cr6dIPvy8xhMftVA1XGt7xfwkJQWLIRbddUKwurKDAmx4dDywwoVr2RVBsVj0vif1ZA
Content-Type: application/json

{
  "pharmacy_id": 1,
  "first_name": "Pharmacy",
  "last_name": "Admin",
  "email": "pharmacyadmin@pharmalink.com",
  "phone": "09123456789",
  "password": "PharmacyAdmin123!"
}

### Login as Pharmacy Admin

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "pharmacyadmin@pharmalink.com",
  "password": "PharmacyAdmin123!"
}


### Test Pharmacy Admin role

GET http://localhost:5000/api/test-role
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5YTk2MmQwMC05NGU2LTQyNGYtYWQwNC02ZjcyYjAwZDY2OGYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NjQyMTc1LCJpYXQiOjE3ODY2Mzg1NzUsImVtYWlsIjoicGhhcm1hY3lhZG1pbkBwaGFybWFsaW5rLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzg2NjM4NTc1fV0sInNlc3Npb25faWQiOiI0NWM1MTE3MS04NmQ1LTRmN2EtOTk5OC0zY2UwZjIxODhjNTYiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.O-L6zFHOJm8tkKZQ-VOXz5xQqF-iY-l3XYVsChYHED19UwswZBGP9gj1mbNUM-KMd-fJucUfSMiqSEzIpozqeg

### Login as Pharmacy Admin

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "pharmacyadmin@pharmalink.com",
  "password": "PharmacyAdmin123!"
}

### Get Pharmacy 1 Inventory

GET http://localhost:5000/api/pharmacies/1/inventory
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5YTk2MmQwMC05NGU2LTQyNGYtYWQwNC02ZjcyYjAwZDY2OGYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2NjQzNTc4LCJpYXQiOjE3ODY2Mzk5NzgsImVtYWlsIjoicGhhcm1hY3lhZG1pbkBwaGFybWFsaW5rLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzg2NjM5OTc4fV0sInNlc3Npb25faWQiOiJlYTRlMjc4MC01NDU4LTQ3YjMtOTRhNy1iNWI1YzMxOWZkMmQiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.JjHUK98due92emw0pCVWEeN7VCywPRN9UIHKAjis6uMLj2yB5NmooSOedVSqxa9Io0VKn5oSES91LcCDzpshrA

### Pharmacy Admin Login

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "pharmacyadmin@pharmalink.com",
  "password": "PharmacyAdmin123!"
}

### Get Pharmacy 1 Inventory - Pharmacy Admin
GET http://localhost:5000/api/pharmacies/1/inventory
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5YTk2MmQwMC05NGU2LTQyNGYtYWQwNC02ZjcyYjAwZDY2OGYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2Njk0MzIyLCJpYXQiOjE3ODY2OTA3MjIsImVtYWlsIjoicGhhcm1hY3lhZG1pbkBwaGFybWFsaW5rLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzg2NjkwNzIyfV0sInNlc3Npb25faWQiOiI1YTA5MzhhMy02ZTkwLTQzMjItYjVjMy02Y2NkNjQxNDhlYWQiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.bCipuv3yUS1OOusN0nVq9C9fH5XvEpVm3KORs4ilQsM_DfKb1Uwl6UGnepAruGK-kfyuPF8hgcYtdoVuEoezfA

### Pharmacy Admin Login

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "pharmacyadmin@pharmalink.com",
  "password": "PharmacyAdmin123!"
}

### Test Supabase connection
GET http://localhost:5000/api/test-users-db

#### Test Supabase connection - get user email
GET http://localhost:5000/api/test-user-email

### Pharmacy Admin Login

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "pharmacyadmin@pharmalink.com",
  "password": "PharmacyAdmin123!"
}
### Pharmacy Admin Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "pharmacyadmin@pharmalink.com",
  "password": "PharmacyAdmin123!"
}

###Pharmacy inventory 1
GET http://localhost:5000/api/pharmacies/1/inventory
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5YTk2MmQwMC05NGU2LTQyNGYtYWQwNC02ZjcyYjAwZDY2OGYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2Njk2MzYzLCJpYXQiOjE3ODY2OTI3NjMsImVtYWlsIjoicGhhcm1hY3lhZG1pbkBwaGFybWFsaW5rLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzg2NjkyNzYzfV0sInNlc3Npb25faWQiOiI3ZTdkYzE2Yi1mYmFjLTRmYzUtYjViZi1lZDM3ZjdkOTU5NjQiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.Utgy8V-WMxPGT26QRMmB9MOXq01ldu00mdcGvEx--u64ogBPvaKHHqjX8TSgg_rZnzC_jrtb1jjSWdgBT2-68g

### Pharmacy Admin Login

POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "pharmacyadmin@pharmalink.com",
  "password": "PharmacyAdmin123!"
}
#### Pharmacy inventory 1
GET http://localhost:5000/api/pharmacies/1/inventory
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiI5YTk2MmQwMC05NGU2LTQyNGYtYWQwNC02ZjcyYjAwZDY2OGYiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg2Njk2OTA3LCJpYXQiOjE3ODY2OTMzMDcsImVtYWlsIjoicGhhcm1hY3lhZG1pbkBwaGFybWFsaW5rLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWxfdmVyaWZpZWQiOnRydWV9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzg2NjkzMzA3fV0sInNlc3Npb25faWQiOiJlYTQzMDlkNC0yY2UxLTQxMzQtYTg2ZC01ZTcxNWE3OWM3ZjciLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.I1CdgfgywL4drALImeUXZ2E8QzPDofTqRB0zABwibrF9aOzXZ00jxa9LamaU4oMRATXPMdzua-nuCSqLTAhTpg
#### Get Super Admin User Info
GET http://localhost:5000/api/users/superadmin

###
POST http://localhost:5000/api/auth/customer-login
Content-Type: application/json

{
  "email": "desamparado@gmail.com",
  "password": "Desamparado123!"
}

###
POST http://localhost:5000/api/reservations
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyZjRjMjk2Ni00NWMyLTRkYTItYTFmNC0yYTdkYWNiZTM3MzgiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg3ODQwNTQ5LCJpYXQiOjE3ODc4MzY5NDksImVtYWlsIjoiZGVzYW1wYXJhZG9AZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3ODc4MzY5NDl9XSwic2Vzc2lvbl9pZCI6ImMzNTQwYzk0LTljMzAtNDQxMi1iY2Y0LWIwN2E5Y2MxNjY5NCIsImlzX2Fub255bW91cyI6ZmFsc2V9.rt2a8-LomAdzX4RDyJzI74zZCUvi_-sdMEUuyYeZrAastqjAbx4JREFILFuNi5vHMfNKRXWEj5BA28yRZUlRoA
Content-Type: application/json

{
  "pharmacy_id": 1,
  "pickup_date": "2026-08-30",
  "pickup_time": "15:00:00",
  "notes": "Test reservation"
}

###
POST http://localhost:5000/api/reservations
Authorization: Bearer eyJhbGciOiJFUzI1NiIsImtpZCI6ImY4ZGI5OTBmLTUwZGItNDJmYy1iZWY2LWI3ZmU3M2QzM2VhOCIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2RtY2txbmJtcmtidGZ4cmhmd2J1LnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIyZjRjMjk2Ni00NWMyLTRkYTItYTFmNC0yYTdkYWNiZTM3MzgiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzg3ODQwNTQ5LCJpYXQiOjE3ODc4MzY5NDksImVtYWlsIjoiZGVzYW1wYXJhZG9AZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJlbWFpbCIsInByb3ZpZGVycyI6WyJlbWFpbCJdfSwidXNlcl9tZXRhZGF0YSI6eyJlbWFpbF92ZXJpZmllZCI6dHJ1ZX0sInJvbGUiOiJhdXRoZW50aWNhdGVkIiwiYWFsIjoiYWFsMSIsImFtciI6W3sibWV0aG9kIjoicGFzc3dvcmQiLCJ0aW1lc3RhbXAiOjE3ODc4MzY5NDl9XSwic2Vzc2lvbl9pZCI6ImMzNTQwYzk0LTljMzAtNDQxMi1iY2Y0LWIwN2E5Y2MxNjY5NCIsImlzX2Fub255bW91cyI6ZmFsc2V9.rt2a8-LomAdzX4RDyJzI74zZCUvi_-sdMEUuyYeZrAastqjAbx4JREFILFuNi5vHMfNKRXWEj5BA28yRZUlRoA
Content-Type: application/json

{
  "pharmacy_id": 1,
  "pickup_date": "2026-08-30",
  "pickup_time": "15:00",
  "notes": "Test reservation with medicine",
  "items": [
    {
      "medicine_id": 1,
      "quantity": 2
    }
  ]
}