-- Pharmacy Management System
-- PostgreSQL schema.sql
-- Scope: Super Admin, Pharmacy Admin/Staff, Customer PWA
-- Delivery functionality is intentionally excluded.
-- IDs use GENERATED BY DEFAULT AS IDENTITY as required.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- 1. PHARMACIES
-- ============================================================
CREATE TABLE pharmacies (
    pharmacy_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    address TEXT NOT NULL,
    contact_number VARCHAR(30),
    email VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_pharmacies_name UNIQUE (name),
    CONSTRAINT uq_pharmacies_email UNIQUE (email),
    CONSTRAINT chk_pharmacies_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

-- ============================================================
-- 2. USERS
-- One account table for all roles:
-- SUPER_ADMIN, PHARMACY_ADMIN, PHARMACY_STAFF, CUSTOMER
-- ============================================================
CREATE TABLE users (
    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pharmacy_id INTEGER,
    role VARCHAR(30) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash TEXT NOT NULL,
    phone VARCHAR(30),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ,

    CONSTRAINT fk_users_pharmacy
        FOREIGN KEY (pharmacy_id)
        REFERENCES pharmacies (pharmacy_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_users_email UNIQUE (email),

    CONSTRAINT chk_users_role
        CHECK (role IN (
            'SUPER_ADMIN',
            'PHARMACY_ADMIN',
            'PHARMACY_STAFF',
            'CUSTOMER'
        )),

    CONSTRAINT chk_users_status
        CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING')),

    CONSTRAINT chk_users_pharmacy_role
        CHECK (
            (role IN ('PHARMACY_ADMIN', 'PHARMACY_STAFF') AND pharmacy_id IS NOT NULL)
            OR
            (role IN ('SUPER_ADMIN', 'CUSTOMER') AND pharmacy_id IS NULL)
        )
);

-- ============================================================
-- 3. MEDICINE CATEGORIES
-- ============================================================
CREATE TABLE medicine_categories (
    category_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_medicine_categories_name UNIQUE (name),
    CONSTRAINT chk_medicine_categories_status
        CHECK (status IN ('ACTIVE', 'INACTIVE'))
);

-- ============================================================
-- 4. MEDICINES
-- Global medicine catalog.
-- Pharmacy-specific stock belongs in INVENTORY.
-- ============================================================
CREATE TABLE medicines (
    medicine_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL,
    generic_name VARCHAR(200) NOT NULL,
    brand_name VARCHAR(200),
    dosage VARCHAR(100),
    dosage_form VARCHAR(100) NOT NULL,
    description TEXT,
    requires_prescription BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_medicines_category
        FOREIGN KEY (category_id)
        REFERENCES medicine_categories (category_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT chk_medicines_status
        CHECK (status IN ('ACTIVE', 'INACTIVE')),

    CONSTRAINT chk_medicines_names
        CHECK (
            length(trim(generic_name)) > 0
            OR length(trim(brand_name)) > 0
        )
);

-- ============================================================
-- 5. INVENTORY
-- Pharmacy-specific stock. A row represents a medicine batch
-- at a particular pharmacy.
-- ============================================================
CREATE TABLE inventory (
    inventory_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pharmacy_id INTEGER NOT NULL,
    medicine_id INTEGER NOT NULL,
    batch_number VARCHAR(100) NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    reorder_level INTEGER NOT NULL DEFAULT 0,
    unit_price NUMERIC(12,2) NOT NULL,
    expiration_date DATE,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_inventory_pharmacy
        FOREIGN KEY (pharmacy_id)
        REFERENCES pharmacies (pharmacy_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_inventory_medicine
        FOREIGN KEY (medicine_id)
        REFERENCES medicines (medicine_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_inventory_batch
        UNIQUE (pharmacy_id, medicine_id, batch_number),

    CONSTRAINT chk_inventory_quantity
        CHECK (quantity >= 0),

    CONSTRAINT chk_inventory_reorder_level
        CHECK (reorder_level >= 0),

    CONSTRAINT chk_inventory_unit_price
        CHECK (unit_price >= 0),

    CONSTRAINT chk_inventory_status
        CHECK (status IN ('AVAILABLE', 'LOW_STOCK', 'OUT_OF_STOCK', 'EXPIRED', 'INACTIVE')),

    CONSTRAINT chk_inventory_expiration
        CHECK (expiration_date IS NULL OR expiration_date >= DATE '2000-01-01')
);

-- ============================================================
-- 6. PRESCRIPTIONS
-- Customer-submitted prescription records.
-- ============================================================
CREATE TABLE prescriptions (
    prescription_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    pharmacy_id INTEGER NOT NULL,
    image_url TEXT,
    prescription_date DATE,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    verified_by INTEGER,
    verified_at TIMESTAMPTZ,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_prescriptions_customer
        FOREIGN KEY (customer_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_prescriptions_pharmacy
        FOREIGN KEY (pharmacy_id)
        REFERENCES pharmacies (pharmacy_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_prescriptions_verified_by
        FOREIGN KEY (verified_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_prescriptions_status
        CHECK (status IN (
            'PENDING',
            'UNDER_REVIEW',
            'VERIFIED',
            'REJECTED',
            'EXPIRED',
            'CANCELLED'
        ))
);

-- ============================================================
-- 7. PRESCRIPTION ITEMS
-- ============================================================
CREATE TABLE prescription_items (
    prescription_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prescription_id INTEGER NOT NULL,
    medicine_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    dosage_instructions TEXT,
    duration VARCHAR(100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_prescription_items_prescription
        FOREIGN KEY (prescription_id)
        REFERENCES prescriptions (prescription_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_prescription_items_medicine
        FOREIGN KEY (medicine_id)
        REFERENCES medicines (medicine_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_prescription_item_medicine
        UNIQUE (prescription_id, medicine_id),

    CONSTRAINT chk_prescription_items_quantity
        CHECK (quantity > 0)
);

-- ============================================================
-- 8. MEDICINE REQUESTS
-- Customer requests medicines that may not currently be
-- available in the selected pharmacy.
-- ============================================================
CREATE TABLE medicine_requests (
    medicine_request_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    pharmacy_id INTEGER NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    notes TEXT,
    reviewed_by INTEGER,
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_medicine_requests_customer
        FOREIGN KEY (customer_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_medicine_requests_pharmacy
        FOREIGN KEY (pharmacy_id)
        REFERENCES pharmacies (pharmacy_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_medicine_requests_reviewed_by
        FOREIGN KEY (reviewed_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_medicine_requests_status
        CHECK (status IN (
            'PENDING',
            'UNDER_REVIEW',
            'AVAILABLE',
            'PARTIALLY_AVAILABLE',
            'UNAVAILABLE',
            'FULFILLED',
            'CANCELLED'
        ))
);

-- ============================================================
-- 9. MEDICINE REQUEST ITEMS
-- ============================================================
CREATE TABLE medicine_request_items (
    medicine_request_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medicine_request_id INTEGER NOT NULL,
    medicine_id INTEGER NOT NULL,
    requested_quantity INTEGER NOT NULL,
    available_quantity INTEGER NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_medicine_request_items_request
        FOREIGN KEY (medicine_request_id)
        REFERENCES medicine_requests (medicine_request_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_medicine_request_items_medicine
        FOREIGN KEY (medicine_id)
        REFERENCES medicines (medicine_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_medicine_request_item_medicine
        UNIQUE (medicine_request_id, medicine_id),

    CONSTRAINT chk_medicine_request_items_requested_quantity
        CHECK (requested_quantity > 0),

    CONSTRAINT chk_medicine_request_items_available_quantity
        CHECK (
            available_quantity >= 0
            AND available_quantity <= requested_quantity
        )
);

-- ============================================================
-- 10. RESERVATIONS
-- Pickup reservations. No delivery fields are included.
-- ============================================================
CREATE TABLE reservations (
    reservation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id INTEGER NOT NULL,
    pharmacy_id INTEGER NOT NULL,
    prescription_id INTEGER,
    reservation_date DATE NOT NULL DEFAULT CURRENT_DATE,
    pickup_date DATE NOT NULL,
    pickup_time TIME,
    status VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    notes TEXT,
    confirmed_by INTEGER,
    confirmed_at TIMESTAMPTZ,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_reservations_customer
        FOREIGN KEY (customer_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_reservations_pharmacy
        FOREIGN KEY (pharmacy_id)
        REFERENCES pharmacies (pharmacy_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_reservations_prescription
        FOREIGN KEY (prescription_id)
        REFERENCES prescriptions (prescription_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_reservations_confirmed_by
        FOREIGN KEY (confirmed_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT chk_reservations_status
        CHECK (status IN (
            'PENDING',
            'CONFIRMED',
            'READY_FOR_PICKUP',
            'COMPLETED',
            'CANCELLED',
            'EXPIRED'
        )),

    CONSTRAINT chk_reservations_pickup_date
        CHECK (pickup_date >= reservation_date)
);

-- ============================================================
-- 11. RESERVATION ITEMS
-- ============================================================
CREATE TABLE reservation_items (
    reservation_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id INTEGER NOT NULL,
    medicine_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12,2),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_reservation_items_reservation
        FOREIGN KEY (reservation_id)
        REFERENCES reservations (reservation_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_reservation_items_medicine
        FOREIGN KEY (medicine_id)
        REFERENCES medicines (medicine_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_reservation_item_medicine
        UNIQUE (reservation_id, medicine_id),

    CONSTRAINT chk_reservation_items_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_reservation_items_unit_price
        CHECK (unit_price IS NULL OR unit_price >= 0)
);

-- ============================================================
-- 12. SALES
-- Records completed/processed pharmacy sales.
-- customer_id may be NULL for a walk-in customer.
-- reservation_id may be NULL for a direct/walk-in sale.
-- ============================================================
CREATE TABLE sales (
    sale_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pharmacy_id INTEGER NOT NULL,
    customer_id INTEGER,
    reservation_id INTEGER,
    processed_by INTEGER NOT NULL,
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    payment_method VARCHAR(30) NOT NULL DEFAULT 'CASH',
    payment_status VARCHAR(20) NOT NULL DEFAULT 'PAID',
    status VARCHAR(20) NOT NULL DEFAULT 'COMPLETED',
    sale_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sales_pharmacy
        FOREIGN KEY (pharmacy_id)
        REFERENCES pharmacies (pharmacy_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_sales_customer
        FOREIGN KEY (customer_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_sales_reservation
        FOREIGN KEY (reservation_id)
        REFERENCES reservations (reservation_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_sales_processed_by
        FOREIGN KEY (processed_by)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_sales_reservation
        UNIQUE (reservation_id),

    CONSTRAINT chk_sales_total_amount
        CHECK (total_amount >= 0),

    CONSTRAINT chk_sales_payment_method
        CHECK (payment_method IN (
            'CASH',
            'CARD',
            'E_WALLET',
            'OTHER'
        )),

    CONSTRAINT chk_sales_payment_status
        CHECK (payment_status IN (
            'PENDING',
            'PAID',
            'REFUNDED',
            'CANCELLED'
        )),

    CONSTRAINT chk_sales_status
        CHECK (status IN (
            'PENDING',
            'COMPLETED',
            'CANCELLED',
            'REFUNDED'
        ))
);

-- ============================================================
-- 13. SALE ITEMS
-- ============================================================
CREATE TABLE sale_items (
    sale_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sale_id INTEGER NOT NULL,
    medicine_id INTEGER NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_sale_items_sale
        FOREIGN KEY (sale_id)
        REFERENCES sales (sale_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT fk_sale_items_medicine
        FOREIGN KEY (medicine_id)
        REFERENCES medicines (medicine_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT uq_sale_item_medicine
        UNIQUE (sale_id, medicine_id),

    CONSTRAINT chk_sale_items_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_sale_items_unit_price
        CHECK (unit_price >= 0),

    CONSTRAINT chk_sale_items_subtotal
        CHECK (subtotal >= 0)
);

-- ============================================================
-- 14. NOTIFICATIONS
-- ============================================================
CREATE TABLE notifications (
    notification_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(50) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMPTZ,

    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT chk_notifications_read_at
        CHECK (
            (is_read = FALSE AND read_at IS NULL)
            OR
            (is_read = TRUE AND read_at IS NOT NULL)
        )
);

-- ============================================================
-- 15. AUDIT LOGS
-- Tracks important system actions by authenticated users.
-- ============================================================
CREATE TABLE audit_logs (
    audit_log_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER,
    pharmacy_id INTEGER,
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100),
    entity_id INTEGER,
    description TEXT,
    ip_address INET,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_audit_logs_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_audit_logs_pharmacy
        FOREIGN KEY (pharmacy_id)
        REFERENCES pharmacies (pharmacy_id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

-- ============================================================
-- INDEXES
-- ============================================================

-- Users
CREATE INDEX idx_users_pharmacy_id ON users (pharmacy_id);
CREATE INDEX idx_users_role ON users (role);
CREATE INDEX idx_users_status ON users (status);

-- Medicines
CREATE INDEX idx_medicines_category_id ON medicines (category_id);
CREATE INDEX idx_medicines_generic_name ON medicines (generic_name);
CREATE INDEX idx_medicines_brand_name ON medicines (brand_name);
CREATE INDEX idx_medicines_status ON medicines (status);

-- Inventory
CREATE INDEX idx_inventory_pharmacy_id ON inventory (pharmacy_id);
CREATE INDEX idx_inventory_medicine_id ON inventory (medicine_id);
CREATE INDEX idx_inventory_expiration_date ON inventory (expiration_date);
CREATE INDEX idx_inventory_status ON inventory (status);
CREATE INDEX idx_inventory_pharmacy_medicine
    ON inventory (pharmacy_id, medicine_id);

-- Prescriptions
CREATE INDEX idx_prescriptions_customer_id ON prescriptions (customer_id);
CREATE INDEX idx_prescriptions_pharmacy_id ON prescriptions (pharmacy_id);
CREATE INDEX idx_prescriptions_status ON prescriptions (status);
CREATE INDEX idx_prescriptions_verified_by ON prescriptions (verified_by);

-- Prescription items
CREATE INDEX idx_prescription_items_medicine_id
    ON prescription_items (medicine_id);

-- Medicine requests
CREATE INDEX idx_medicine_requests_customer_id
    ON medicine_requests (customer_id);
CREATE INDEX idx_medicine_requests_pharmacy_id
    ON medicine_requests (pharmacy_id);
CREATE INDEX idx_medicine_requests_status
    ON medicine_requests (status);

-- Medicine request items
CREATE INDEX idx_medicine_request_items_medicine_id
    ON medicine_request_items (medicine_id);

-- Reservations
CREATE INDEX idx_reservations_customer_id
    ON reservations (customer_id);
CREATE INDEX idx_reservations_pharmacy_id
    ON reservations (pharmacy_id);
CREATE INDEX idx_reservations_prescription_id
    ON reservations (prescription_id);
CREATE INDEX idx_reservations_status
    ON reservations (status);
CREATE INDEX idx_reservations_pickup_date
    ON reservations (pickup_date);

-- Reservation items
CREATE INDEX idx_reservation_items_medicine_id
    ON reservation_items (medicine_id);

-- Sales
CREATE INDEX idx_sales_pharmacy_id ON sales (pharmacy_id);
CREATE INDEX idx_sales_customer_id ON sales (customer_id);
CREATE INDEX idx_sales_processed_by ON sales (processed_by);
CREATE INDEX idx_sales_sale_date ON sales (sale_date);
CREATE INDEX idx_sales_status ON sales (status);

-- Sale items
CREATE INDEX idx_sale_items_medicine_id
    ON sale_items (medicine_id);

-- Notifications
CREATE INDEX idx_notifications_user_id
    ON notifications (user_id);
CREATE INDEX idx_notifications_is_read
    ON notifications (is_read);
CREATE INDEX idx_notifications_created_at
    ON notifications (created_at);

-- Audit logs
CREATE INDEX idx_audit_logs_user_id
    ON audit_logs (user_id);
CREATE INDEX idx_audit_logs_pharmacy_id
    ON audit_logs (pharmacy_id);
CREATE INDEX idx_audit_logs_entity
    ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_audit_logs_created_at
    ON audit_logs (created_at);

-- ============================================================
-- UPDATED_AT TRIGGER
-- Automatically refreshes updated_at whenever a row changes.
-- ============================================================

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_pharmacies_updated_at
BEFORE UPDATE ON pharmacies
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_medicine_categories_updated_at
BEFORE UPDATE ON medicine_categories
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_medicines_updated_at
BEFORE UPDATE ON medicines
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_inventory_updated_at
BEFORE UPDATE ON inventory
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_prescriptions_updated_at
BEFORE UPDATE ON prescriptions
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_medicine_requests_updated_at
BEFORE UPDATE ON medicine_requests
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_medicine_request_items_updated_at
BEFORE UPDATE ON medicine_request_items
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_reservations_updated_at
BEFORE UPDATE ON reservations
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_sales_updated_at
BEFORE UPDATE ON sales
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ============================================================
-- BASIC ROLE-BASED DATA INTEGRITY TRIGGERS
-- These prevent assigning a customer as a prescription verifier,
-- or a non-pharmacy user as a pharmacy processor.
-- ============================================================

CREATE OR REPLACE FUNCTION validate_pharmacy_staff_user()
RETURNS TRIGGER AS $$
DECLARE
    target_role VARCHAR(30);
    target_pharmacy INTEGER;
BEGIN
    SELECT role, pharmacy_id
    INTO target_role, target_pharmacy
    FROM users
    WHERE user_id = NEW.user_id;

    IF target_role IS NULL THEN
        RAISE EXCEPTION 'User % does not exist', NEW.user_id;
    END IF;

    IF target_role NOT IN ('PHARMACY_ADMIN', 'PHARMACY_STAFF', 'SUPER_ADMIN') THEN
        RAISE EXCEPTION 'User % is not authorized for pharmacy operations', NEW.user_id;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION validate_prescription_verifier()
RETURNS TRIGGER AS $$
DECLARE
    verifier_role VARCHAR(30);
    verifier_pharmacy INTEGER;
BEGIN
    IF NEW.verified_by IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT role, pharmacy_id
    INTO verifier_role, verifier_pharmacy
    FROM users
    WHERE user_id = NEW.verified_by;

    IF verifier_role IS NULL THEN
        RAISE EXCEPTION 'Verifier user % does not exist', NEW.verified_by;
    END IF;

    IF verifier_role NOT IN ('PHARMACY_ADMIN', 'PHARMACY_STAFF', 'SUPER_ADMIN') THEN
        RAISE EXCEPTION 'User % cannot verify prescriptions', NEW.verified_by;
    END IF;

    IF verifier_role <> 'SUPER_ADMIN'
       AND verifier_pharmacy IS DISTINCT FROM NEW.pharmacy_id THEN
        RAISE EXCEPTION 'Verifier does not belong to the prescription pharmacy';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_prescriptions_validate_verifier
BEFORE INSERT OR UPDATE ON prescriptions
FOR EACH ROW EXECUTE FUNCTION validate_prescription_verifier();

CREATE OR REPLACE FUNCTION validate_medicine_request_reviewer()
RETURNS TRIGGER AS $$
DECLARE
    reviewer_role VARCHAR(30);
    reviewer_pharmacy INTEGER;
BEGIN
    IF NEW.reviewed_by IS NULL THEN
        RETURN NEW;
    END IF;

    SELECT role, pharmacy_id
    INTO reviewer_role, reviewer_pharmacy
    FROM users
    WHERE user_id = NEW.reviewed_by;

    IF reviewer_role IS NULL THEN
        RAISE EXCEPTION 'Reviewer user % does not exist', NEW.reviewed_by;
    END IF;

    IF reviewer_role NOT IN ('PHARMACY_ADMIN', 'PHARMACY_STAFF', 'SUPER_ADMIN') THEN
        RAISE EXCEPTION 'User % cannot review medicine requests', NEW.reviewed_by;
    END IF;

    IF reviewer_role <> 'SUPER_ADMIN'
       AND reviewer_pharmacy IS DISTINCT FROM NEW.pharmacy_id THEN
        RAISE EXCEPTION 'Reviewer does not belong to the request pharmacy';
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_medicine_requests_validate_reviewer
BEFORE INSERT OR UPDATE ON medicine_requests
FOR EACH ROW EXECUTE FUNCTION validate_medicine_request_reviewer();

-- ============================================================
-- FINALIZE
-- ============================================================

COMMIT;
