const { generateCustomerReply } = require('../services/aiService')

const {
  searchKnowledge,
} = require('../services/aiKnowledgeService')

const {
  resolveCustomerDataContext,
} = require('../services/aiDataContextService')

const {
  resolveNavigationAction,
} = require('../services/aiNavigationService')

const {
  getConversationForCustomer,
  saveExchangeAtomic,
  getConversationMessages,
  getCustomerConversations,
  getConversationWithMessages,
  closeConversation,
} = require('../services/aiConversationService')

const MAX_MESSAGE_LENGTH = 2000

const isValidId = (value) => {
  const number = Number(value)

  return Number.isInteger(number) && number > 0
}

const createConversationTitle = (message) => {
  const cleanMessage = message
    .replace(/\s+/g, ' ')
    .trim()

  if (cleanMessage.length <= 60) {
    return cleanMessage
  }

  return `${cleanMessage.slice(0, 57)}...`
}

/* ============================================================
   CHAT
============================================================ */

const chat = async (req, res) => {
  try {
    const { message, conversationId } = req.body

    /* ============================================================
       VALIDATE MESSAGE
    ============================================================ */

    if (typeof message !== 'string') {
      return res.status(400).json({
        success: false,
        message: 'Message must be a string',
      })
    }

    const trimmedMessage = message.trim()

    if (!trimmedMessage) {
      return res.status(400).json({
        success: false,
        message: 'Message is required',
      })
    }

    if (trimmedMessage.length > MAX_MESSAGE_LENGTH) {
      return res.status(400).json({
        success: false,
        message: `Message must not exceed ${MAX_MESSAGE_LENGTH} characters`,
      })
    }

    /*
     * authenticateUser + loadPharmaUser have already loaded
     * the authenticated PharmaLink customer.
     *
     * Never accept customer_id from the frontend.
     */
    const customerId = req.pharmaUser?.user_id

    if (!customerId) {
      return res.status(401).json({
        success: false,
        message:
          'Customer account could not be identified',
      })
    }

    /* ============================================================
       CONVERSATION
    ============================================================ */

    let conversation = null
    let conversationHistory = []

    /*
     * Existing conversation:
     *
     * Verify ownership and load its existing history.
     */
    if (
      conversationId !== undefined &&
      conversationId !== null
    ) {
      if (!isValidId(conversationId)) {
        return res.status(400).json({
          success: false,
          message: 'Invalid conversation ID',
        })
      }

      conversation =
        await getConversationForCustomer(
          Number(conversationId),
          customerId
        )

      if (!conversation) {
        return res.status(404).json({
          success: false,
          message: 'Conversation not found',
        })
      }

      if (conversation.status !== 'ACTIVE') {
        return res.status(409).json({
          success: false,
          message: 'This conversation is closed',
        })
      }

      /*
       * Load previous messages before generating the next
       * response.
       */
      conversationHistory =
        await getConversationMessages(
          conversation.conversation_id,
          20
        )
    } else {
      /*
       * IMPORTANT:
       *
       * Do NOT create the database conversation yet.
       *
       * The AI provider must successfully generate a reply
       * first. This prevents failed provider requests from
       * creating empty/customer-only conversations.
       */
      conversationHistory = []
    }

    /* ============================================================
       VERIFIED PHARMALINK KNOWLEDGE
    ============================================================ */

    const relevantKnowledge =
      await searchKnowledge(
        trimmedMessage,
        5
      )

    /* ============================================================
       CONTROLLED LIVE PHARMALINK DATA
    ============================================================ */

    /*
     * SECURITY:
     *
     * customerId comes only from authenticated middleware.
     * It is never accepted from req.body or generated by the
     * AI provider.
     */
    const liveDataContext =
      await resolveCustomerDataContext({
        message: trimmedMessage,
        customerId,
      })

    /* ============================================================
       CONTROLLED NAVIGATION ACTION
    ============================================================ */

    /*
     * Navigation actions are resolved deterministically by
     * PharmaLink.
     *
     * DeepSeek/Gemini does not generate routes, URLs, or
     * navigation targets.
     */
    const navigationAction =
      resolveNavigationAction(trimmedMessage)

    /* ============================================================
       GENERATE AI RESPONSE FIRST
    ============================================================ */

    /*
     * No new customer message has been persisted yet.
     *
     * If the selected AI provider fails here, the request
     * returns an error without leaving a customer-only
     * message behind.
     */
    const reply = await generateCustomerReply(
      trimmedMessage,
      conversationHistory,
      relevantKnowledge,
      liveDataContext
    )

    /* ============================================================
       PERSIST SUCCESSFUL EXCHANGE
    ============================================================ */

    const savedExchange =
      await saveExchangeAtomic({
        customerId,

        conversationId:
          conversation?.conversation_id ??
          null,

        title:
          conversation
            ? null
            : createConversationTitle(
                trimmedMessage
              ),

        customerMessage:
          trimmedMessage,

        assistantMessage:
          reply,

        customerMessageType:
          'GENERAL',

        assistantMessageType:
          'GENERAL',
      })

    /* ============================================================
       RESPONSE
    ============================================================ */

    return res.status(200).json({
      success: true,

      data: {
        conversationId:
          savedExchange.conversationId,

        reply,

        /*
         * Safe ephemeral UI metadata.
         *
         * This action was generated by PharmaLink's
         * deterministic navigation resolver, not by the
         * external AI provider.
         *
         * It is intentionally not persisted in ai_messages.
         */
        action: navigationAction,
      },
    })
  } catch (error) {
    console.error(
      'AI controller error:',
      error
    )

    /* ============================================================
       AI PROVIDER ERRORS
    ============================================================ */

    if (error.code === 'AI_NOT_CONFIGURED') {
      return res.status(503).json({
        success: false,
        message:
          'PharmaLink Assistant is currently unavailable',
      })
    }

    if (error.code === 'AI_EMPTY_RESPONSE') {
      return res.status(502).json({
        success: false,
        message:
          'PharmaLink Assistant could not generate a response. Please try again.',
      })
    }

    if (
      error.code ===
      'AI_SERVICE_UNAVAILABLE'
    ) {
      return res.status(503).json({
        success: false,
        message:
          'PharmaLink Assistant is temporarily busy. Please try again in a moment.',
      })
    }

    if (
      error.code ===
      'AI_QUOTA_EXHAUSTED'
    ) {
      return res.status(429).json({
        success: false,
        message:
          'PharmaLink Assistant usage is temporarily limited. Please try again later.',
      })
    }

    if (
      error.code ===
      'AI_RATE_LIMITED'
    ) {
      return res.status(429).json({
        success: false,
        message:
          'PharmaLink Assistant is receiving too many requests right now. Please wait a moment and try again.',
      })
    }

    if (error.code === 'AI_SERVICE_ERROR') {
      return res.status(503).json({
        success: false,
        message:
          'PharmaLink Assistant is temporarily unavailable. Please try again later.',
      })
    }

    /* ============================================================
       KNOWLEDGE / HISTORY ERRORS
    ============================================================ */

    if (
      error.code ===
      'AI_KNOWLEDGE_FETCH_ERROR'
    ) {
      return res.status(500).json({
        success: false,
        message:
          'PharmaLink knowledge could not be retrieved. Please try again.',
      })
    }

    if (
      error.code ===
      'AI_MESSAGES_FETCH_ERROR'
    ) {
      return res.status(500).json({
        success: false,
        message:
          'Conversation history could not be retrieved. Please try again.',
      })
    }

    /* ============================================================
       CONVERSATION ERRORS
    ============================================================ */

    if (
      error.code ===
        'AI_CONVERSATION_FETCH_ERROR'
    ) {
      return res.status(500).json({
        success: false,
        message:
          'The conversation could not be retrieved. Please try again.',
      })
    }

    if (
      error.code ===
      'AI_EXCHANGE_SAVE_ERROR'
    ) {
      return res.status(500).json({
        success: false,
        message:
          'PharmaLink Assistant could not save the conversation. Please try again.',
      })
    }

    if (
      error.code ===
      'AI_CONVERSATION_NOT_FOUND'
    ) {
      return res.status(404).json({
        success: false,
        message:
          'Conversation not found.',
      })
    }

    if (
      error.code ===
      'AI_CONVERSATION_CLOSED'
    ) {
      return res.status(409).json({
        success: false,
        message:
          'This conversation is closed. Start a new conversation to continue.',
      })
    }

    /* ============================================================
       LIVE DATA ERRORS
    ============================================================ */

    const liveDataErrorCodes = [
      'AI_CUSTOMER_REQUIRED',

      'AI_MEDICINE_SEARCH_ERROR',
      'AI_MEDICINE_FETCH_ERROR',
      'AI_PHARMACY_AVAILABILITY_ERROR',

      'AI_RESERVATIONS_FETCH_ERROR',
      'AI_RESERVATION_FETCH_ERROR',

      'AI_PRESCRIPTIONS_FETCH_ERROR',
      'AI_PRESCRIPTION_FETCH_ERROR',

      'AI_MEDICINE_REQUESTS_FETCH_ERROR',
      'AI_MEDICINE_REQUEST_FETCH_ERROR',
    ]

    if (
      liveDataErrorCodes.includes(
        error.code
      )
    ) {
      return res.status(500).json({
        success: false,
        message:
          'PharmaLink live information could not be retrieved. Please try again.',
      })
    }

    /* ============================================================
       UNEXPECTED ERROR
    ============================================================ */

    return res.status(500).json({
      success: false,
      message:
        'An unexpected server error occurred',
    })
  }
}

/* ============================================================
   LIST CUSTOMER CONVERSATIONS
============================================================ */

const listConversations = async (req, res) => {
  try {
    const customerId = req.pharmaUser?.user_id

    if (!customerId) {
      return res.status(401).json({
        success: false,
        message:
          'Customer account could not be identified',
      })
    }

    const conversations =
      await getCustomerConversations(
        customerId
      )

    return res.status(200).json({
      success: true,

      data: {
        conversations,
      },
    })
  } catch (error) {
    console.error(
      'List AI conversations error:',
      error
    )

    return res.status(500).json({
      success: false,
      message:
        'AI conversations could not be retrieved',
    })
  }
}

/* ============================================================
   GET CUSTOMER CONVERSATION
============================================================ */

const getConversation = async (req, res) => {
  try {
    const customerId = req.pharmaUser?.user_id
    const { conversationId } = req.params

    if (!customerId) {
      return res.status(401).json({
        success: false,
        message:
          'Customer account could not be identified',
      })
    }

    if (!isValidId(conversationId)) {
      return res.status(400).json({
        success: false,
        message: 'Invalid conversation ID',
      })
    }

    const conversation =
      await getConversationWithMessages(
        Number(conversationId),
        customerId
      )

    if (!conversation) {
      return res.status(404).json({
        success: false,
        message: 'Conversation not found',
      })
    }

    return res.status(200).json({
      success: true,

      data: {
        conversation,
      },
    })
  } catch (error) {
    console.error(
      'Get AI conversation error:',
      error
    )

    return res.status(500).json({
      success: false,
      message:
        'AI conversation could not be retrieved',
    })
  }
}

/* ============================================================
   CLOSE CUSTOMER CONVERSATION
============================================================ */

const closeCustomerConversation = async (
  req,
  res
) => {
  try {
    const customerId = req.pharmaUser?.user_id
    const { conversationId } = req.params

    if (!customerId) {
      return res.status(401).json({
        success: false,
        message:
          'Customer account could not be identified',
      })
    }

    if (!isValidId(conversationId)) {
      return res.status(400).json({
        success: false,
        message: 'Invalid conversation ID',
      })
    }

    const conversation =
      await closeConversation(
        Number(conversationId),
        customerId
      )

    if (!conversation) {
      return res.status(404).json({
        success: false,
        message: 'Conversation not found',
      })
    }

    return res.status(200).json({
      success: true,

      data: {
        conversation,
      },
    })
  } catch (error) {
    console.error(
      'Close AI conversation error:',
      error
    )

    if (
      error.code ===
      'AI_CONVERSATION_CLOSE_ERROR'
    ) {
      return res.status(500).json({
        success: false,
        message:
          'The conversation could not be closed. Please try again.',
      })
    }

    return res.status(500).json({
      success: false,
      message:
        'An unexpected server error occurred',
    })
  }
}

module.exports = {
  chat,
  listConversations,
  getConversation,
  closeCustomerConversation,
}