// File: superadmin-web/src/pages/ReportsPage.jsx

import { useMemo, useState } from 'react'
import { FileText, Search } from 'lucide-react'
import './ReportsPage.css'

const reports = [
  {
    id: 1,
    name: 'Pharmacy Registration Report',
    type: 'Pharmacy',
    generatedBy: 'Super Admin',
    date: '2026-09-24',
    status: 'Completed',
  },
  {
    id: 2,
    name: 'User Activity Report',
    type: 'User Activity',
    generatedBy: 'Super Admin',
    date: '2026-09-24',
    status: 'Completed',
  },
  {
    id: 3,
    name: 'System Usage Report',
    type: 'System',
    generatedBy: 'Super Admin',
    date: '2026-09-23',
    status: 'Completed',
  },
  {
    id: 4,
    name: 'Pharmacy Status Report',
    type: 'Pharmacy',
    generatedBy: 'Super Admin',
    date: '2026-09-22',
    status: 'Completed',
  },
  {
    id: 5,
    name: 'Administrative Activity Report',
    type: 'Administration',
    generatedBy: 'Super Admin',
    date: '2026-09-21',
    status: 'Completed',
  },
  {
    id: 6,
    name: 'User Registration Report',
    type: 'User Activity',
    generatedBy: 'Super Admin',
    date: '2026-09-20',
    status: 'Completed',
  },
]

export function ReportsPage() {
  const [search, setSearch] = useState('')
  const [currentPage, setCurrentPage] = useState(1)

  const reportsPerPage = 5

  const filteredReports = useMemo(() => {
    const query = search.trim().toLowerCase()

    if (!query) return reports

    return reports.filter((report) =>
      [
        report.name,
        report.type,
        report.generatedBy,
        report.date,
        report.status,
      ].some((value) =>
        String(value || '').toLowerCase().includes(query)
      )
    )
  }, [search])

  const totalPages = Math.ceil(
    filteredReports.length / reportsPerPage
  )

  const startIndex = (currentPage - 1) * reportsPerPage

  const displayedReports = filteredReports.slice(
    startIndex,
    startIndex + reportsPerPage
  )

  const handleSearch = (event) => {
    setSearch(event.target.value)
    setCurrentPage(1)
  }

  return (
    <div className="reports-page">
      <div className="page-header">
        <div>
          <div className="page-title-row">
            <FileText size={24} />
            <h1>Reports</h1>
          </div>

          <p>
            View generated reports and system information.
          </p>
        </div>

        <div className="report-count">
          {reports.length} reports
        </div>
      </div>

      <div className="reports-toolbar">
        <div className="search-box">
          <Search size={18} />

          <input
            type="text"
            placeholder="Search reports..."
            value={search}
            onChange={handleSearch}
          />
        </div>
      </div>

      <div className="reports-table-card">
        {displayedReports.length === 0 ? (
          <div className="reports-table-state">
            {search
              ? 'No reports match your search.'
              : 'No reports found.'}
          </div>
        ) : (
          <div className="reports-table-wrapper">
            <table className="reports-table">
              <thead>
                <tr>
                  <th>Report</th>
                  <th>Type</th>
                  <th>Generated By</th>
                  <th>Date</th>
                  <th>Status</th>
                </tr>
              </thead>

              <tbody>
                {displayedReports.map((report) => (
                  <tr key={report.id}>
                    <td>
                      <strong>{report.name}</strong>
                    </td>

                    <td>
                      <span className="report-type">
                        {report.type}
                      </span>
                    </td>

                    <td>{report.generatedBy}</td>

                    <td>{report.date}</td>

                    <td>
                      <span className="report-status">
                        {report.status}
                      </span>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>

      {filteredReports.length > 0 && (
        <div className="reports-footer">
          <span>
            Showing {startIndex + 1}–
            {Math.min(
              startIndex + reportsPerPage,
              filteredReports.length
            )}{' '}
            of {filteredReports.length} reports
          </span>

          <div className="reports-pagination">
            <button
              type="button"
              onClick={() =>
                setCurrentPage((page) => Math.max(page - 1, 1))
              }
              disabled={currentPage === 1}
            >
              Previous
            </button>

            <span>
              Page {currentPage} of {Math.max(totalPages, 1)}
            </span>

            <button
              type="button"
              onClick={() =>
                setCurrentPage((page) =>
                  Math.min(page + 1, totalPages)
                )
              }
              disabled={currentPage >= totalPages}
            >
              Next
            </button>
          </div>
        </div>
      )}
    </div>
  )
}